version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: app.app
- url: /cron/soc
  script: cron.app
  login: admin
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
