version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: app.app
- url: /faq
  script: app.app
- url: /cron/soc
  script: cron.app
  login: admin
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
- url: /static
  static_dir: static

env_variables:
  semester: '92015'
